const LANGUAGE = 'StudyAppLanguage';
const STATUS_PERMISSION = 'STATUS_PERMISSION';
const STATUS_RECORD = 'STATUS_RECORD';
const STATUS_PROCESS = 'STATUS_PROCESS';

export default {
	LANGUAGE,
	STATUS_PERMISSION,
	STATUS_RECORD,
	STATUS_PROCESS
};
